AllCops:
  Exclude:
    - db/schema.rb
    - Gemfile
    - bin/**/*
    - vendor/

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Style/Next:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

# Needed for Pundit headless policies
Style/StructInheritance:
  Enabled: false

Rails:
  Enabled: true
